### ISSUE TITLE
Symcon Flowhandler schmeisst kontinuierlich Fehlermeldungen

### ISSUE THREAD

**Issue by strozycn** [roastedelectrons/HoymilesOpenDTU#1]
Hallo Tobias, 

vielen Dank für Dein Symcon-Modul! Die Einrichtung ist ein Traum und es geht im Handumdrehen.

Ich habe aktuell 2 HM Wechselrichter via openDTU im Zugriff, die ich ins IPS eingebunden haben.
Datenaustausch usw. funktioniert alles ohne Probleme

Meine Freude ist allerdings ein wenig getrübt - nach 3 Wochen des Einsatzes habe ich 2 Verhalten im Kontext des Konfiguratormoduls festgestellt, wo wir mal genauer draufschauen sollten.

**FlowHandler:**
Ich erhalten im 5-Sekundentakt (vermutlich entsprechend dem mqtt-Intervall) jeweils 6 Einträge des FlowHandlers:
![image](https://user-images.githubusercontent.com/121042430/211312334-f8e065ec-ea25-4848-8d62-f28fa1160202.png)

Exemplarisch eine Meldung erweitert:
![image](https://user-images.githubusercontent.com/121042430/211312449-b4b033be-eb12-4472-bfbb-1037fd69ab19.png)

Zehntausende Fehlermeldungen jeden Tag sind etwas unschön .. :-)

**Objektbaum**
Im Objektbaum kann ich den OpenDTU Configurator in der Folge auch nicht mehr starten, ich erhalte eine vergleichbare Fehlermeldung:

![image](https://user-images.githubusercontent.com/121042430/211312970-83299424-ded7-485b-956d-f9d57f76f927.png)

Installiere ich das Modul neu, kann es vorkommen, dass er die OpenDTU und die beiden WR anzeigt, jedoch mit dem Verweis "nicht erreichbar" - wobei die openDTU erreichbar ist und beide WR aktiv sind. (extra tagsüber nochmals ausprobiert.)

In seltenen Fällen - nach mehrfachem Entfernen und Neuinstallation, zeigt er den openDTU-Controller mit IP-Adresse an, WR ebenfalls erreichbar. 
ABER: mit klicken auf "Aktualisieren" kommt anschließend sofort die Meldung "Konnte Konfigurationsform nicht laden" - Invalid argument supplied ... line 165

Hat jemand anders mit mehr als 1 Wechselrichter ähnliche Erfahrungen gemacht?

Welche Informationen sind weiter hilfreich um den Fehler einzugrenzen?
Meine Konfiguration: Symcon 6.3, 29.11.2022 im Docker Container

VG,
Carsten

**Comment by roastedelectrons** [comment]
Danke für deinen ausführlichen Fehlerbericht. Ich habe noch zwei Rückfragen:
1. Tritt der Fehler erst seit einem Update auf Symcon 6.3.X auf?
2. Kommt im Namen, den du für den Wechselrichter in OpenDTU vergeben hast ein Umlaut oder Sonderzeichen vor (im Screenshot hast du diese unkenntlich gemacht)?

Ich vermute hier ein Problem mit UTF8 Codierung, das seit einer Veränderung der Verarbeitung von MQTT-Nachrichten in 6.3 auftreten kann.
Du kannst solange den Konfigurator auch löschen - er ist für die Funktion nicht erforderlich.

**Comment by strozycn** [comment]
OK, voll reingefallen - ich hab Dir (natürlich) ein 'ü' im Wechselrichternamen unterschlagen!
Das ist tatsächlich dann mein Fehler im Schritt davor gewesen!

Ich hatte dem Namen keine weitere Bedeutung geschenkt, da mqtt-seitig das Topic ja 
eigentlich an der Seriennummer hängt.

Die Frage nach der Version kann ich leider nicht beantworten, zuerst das IPS Update, dann kam 
2 Wochen später die DTU dazu...

Besten Dank für die schnelle Reaktion und Deinem entscheidenden Hinweis!

**Comment by roastedelectrons** [comment]
Ich habe ein paar Änderungen vorgenommen, sodass der Konfigurator nun auch korrekt bei Umlauten in Namen und Topics arbeitet.
2e80111edffd760dbb07a286b4a2cbecdd8026c7
