### ISSUE TITLE
HOYMILES_SetLimitAbsolute ohne Funktion

### ISSUE THREAD

**Issue by Chilled** [roastedelectrons/HoymilesOpenDTU#2]
Hallo,

ich habe das Modul erfolgreich eingerichtet und bekomme auch alle Werte der openDTU übertragen. Allerdings wollte ich eine Nulleinspeisung realisieren. Die Funktion HOYMILES_SetLimitAbsolute setzt jedoch leider kein Limit. In der DTU selbst kann ich von Hand ein Limit eintragen. Es gibt auch keine Fehlermeldung.

Bei der Funktion HOYMILES_SetLimitAbsolutePersistent kommt dann
`Fatal error: Uncaught Error: Call to undefined function HOYMILES_SetLimitAbsolutePersistent() in /var/lib/symcon/scripts/29722.ips.php:25
Stack trace:
#0 {main}
  thrown in /var/lib/symcon/scripts/29722.ips.php on line 25`

**Comment by roastedelectrons** [comment]
Welche OpenDTU Version benutzt du? Ich kann den Fehler hier nicht nachstellen. Du musst ggf. etwas warten, bis die Limit-Werte auch übernommen werden. Der Wechselrichter muss zwingend auch produzieren, sonst sind keine Einstellungen möglich.

Die Funktion um persistente Werte zu setzten lautet korrekt: HOYMILES_SetLimitPersistentAbsolute. Dies ist ein Fehler in der Doku.

**Comment by Chilled** [comment]
Den Doku Fehler hab ich schon ausgemacht. Ich würde das ganze auch lieber nonpersistent setzen. Hab jetzt mal mit nem MQTT Analyzer nachgeschaut. Also der cmd Wert wird gesetzt. Liegt offenbar an der openDTU oder an meiner Verbindung. Aber connected ist die DTU ja. Werte werden aktualisiert. Und ich prüfe auch ob überhaupt produziert wird. Kann es mir aktuell nicht erklären. DTU version lautet bf05dc8
Liegt aber wohl doch eher an der DTU. Hab dort mal eine Diskussion gestartet [https://github.com/tbnobody/OpenDTU/discussions/748](https://github.com/tbnobody/OpenDTU/discussions/748)

**Comment by roastedelectrons** [comment]
Funktioniert es denn mit dem persistenten setzten der Werte aus dem Modul heraus?

**Comment by Chilled** [comment]
Ok.... hat sich erledigt. Ein Reset der DTU brachte Erfolg. Jetzt funktioniert alles wie gewünscht. Trotzdem danke
